name: CodeRed Cloud Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to CodeRed Cloud
        uses: coderedcorp/codered-cloud-deploy@v1
        with:
          app-id: alkawtharuniversity
          api-token: ${{ secrets.CR_TOKEN }}
