name: CodeRed Cloud Deploy

on:
  push:
    branches:
      - main  # Ya jo bhi tumhara branch hai

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to CodeRed Cloud
        uses: coderedcorp/codered-cloud-deploy@v1
        with:
          app-id: ${{ alkawtharuniversity }}
          api-token: ${{ FkaU23IVGa4LTWAfb2vuyMyUATGxzLjt }}
