name: CodeRed Cloud Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install CodeRed CLI
        run: |
          wget -nv -O /usr/local/bin/cr https://www.codered.cloud/cli/cr-linux
          chmod +x /usr/local/bin/cr

      - name: Deploy to CodeRed Cloud
        run: cr deploy "Al-Kawthar University"
        env:
          CR_TOKEN: ${{ secrets.CR_TOKEN }}
